name: Bulk Docker Image Sync

on:
  workflow_dispatch: # 手动触发

jobs:
  sync-images:
    runs-on: ubuntu-latest
    strategy:
      # 矩阵配置：在这里列出所有你想要拉取的镜像
      matrix:
        include:
          - remote: "mswebench/ponylang_m_ponyc:pr-1485"
          - remote: "mswebench/ponylang_m_ponyc:pr-1460"
          - remote: "mswebench/ponylang_m_ponyc:pr-1354"
          - remote: "mswebench/ponylang_m_ponyc:pr-1257"
          - remote: "mswebench/ponylang_m_ponyc:pr-1172"
          - remote: "mswebench/ponylang_m_ponyc:pr-1170"
          - remote: "mswebench/ponylang_m_ponyc:pr-933"
          - remote: "mswebench/ponylang_m_ponyc:pr-907"
          - remote: "mswebench/ponylang_m_ponyc:pr-904"
          - remote: "mswebench/ponylang_m_ponyc:pr-890"
          - remote: "mswebench/ponylang_m_ponyc:pr-880"
          - remote: "mswebench/ponylang_m_ponyc:pr-878"
          - remote: "mswebench/ponylang_m_ponyc:pr-860"
          - remote: "mswebench/redis_m_redis:pr-13711"
          - remote: "mswebench/redis_m_redis:pr-13449"
          - remote: "mswebench/redis_m_redis:pr-13338"
          - remote: "mswebench/redis_m_redis:pr-13311"
          - remote: "mswebench/redis_m_redis:pr-13263"
          - remote: "mswebench/redis_m_redis:pr-13117"
          - remote: "mswebench/redis_m_redis:pr-13115"
          - remote: "mswebench/redis_m_redis:pr-13042"
          - remote: "mswebench/redis_m_redis:pr-13004"
          - remote: "mswebench/redis_m_redis:pr-12958"
          - remote: "mswebench/redis_m_redis:pr-12893"
          - remote: "mswebench/valkey-io_m_valkey:pr-1694"
          - remote: "mswebench/valkey-io_m_valkey:pr-1684"
          - remote: "mswebench/valkey-io_m_valkey:pr-1613"
          - remote: "mswebench/valkey-io_m_valkey:pr-1553"
          - remote: "mswebench/valkey-io_m_valkey:pr-1520"
          - remote: "mswebench/valkey-io_m_valkey:pr-1516"
          - remote: "mswebench/valkey-io_m_valkey:pr-1508"
          - remote: "mswebench/valkey-io_m_valkey:pr-1499"
          - remote: "mswebench/valkey-io_m_valkey:pr-1497"
          - remote: "mswebench/valkey-io_m_valkey:pr-1479"
          - remote: "mswebench/valkey-io_m_valkey:pr-1398"
          - remote: "mswebench/valkey-io_m_valkey:pr-1371"
          - remote: "mswebench/valkey-io_m_valkey:pr-1317"
          - remote: "mswebench/valkey-io_m_valkey:pr-1312"
          - remote: "mswebench/valkey-io_m_valkey:pr-1260"
          - remote: "mswebench/valkey-io_m_valkey:pr-1186"
          - remote: "mswebench/valkey-io_m_valkey:pr-1063"
          - remote: "mswebench/valkey-io_m_valkey:pr-1031"
          - remote: "mswebench/valkey-io_m_valkey:pr-981"
          - remote: "mswebench/valkey-io_m_valkey:pr-944"
          - remote: "mswebench/valkey-io_m_valkey:pr-928"
          - remote: "mswebench/valkey-io_m_valkey:pr-901"
          - remote: "mswebench/valkey-io_m_valkey:pr-871"
          - remote: "mswebench/valkey-io_m_valkey:pr-809"
          - remote: "mswebench/valkey-io_m_valkey:pr-790"
          - remote: "mswebench/valkey-io_m_valkey:pr-754"
          - remote: "mswebench/valkey-io_m_valkey:pr-736"
          - remote: "mswebench/valkey-io_m_valkey:pr-688"
          - remote: "mswebench/valkey-io_m_valkey:pr-586"
          - remote: "mswebench/valkey-io_m_valkey:pr-584"
          - remote: "mswebench/valkey-io_m_valkey:pr-556"
          - remote: "mswebench/valkey-io_m_valkey:pr-554"
          - remote: "mswebench/valkey-io_m_valkey:pr-515"
          - remote: "mswebench/valkey-io_m_valkey:pr-501"
          - remote: "mswebench/valkey-io_m_valkey:pr-445"
          - remote: "mswebench/valkey-io_m_valkey:pr-378"
          - remote: "mswebench/valkey-io_m_valkey:pr-306"
          - remote: "mswebench/valkey-io_m_valkey:pr-223"
          - remote: "mswebench/valkey-io_m_valkey:pr-206"
          - remote: "mswebench/cgal_m_cgal:pr-8736"
          - remote: "mswebench/cgal_m_cgal:pr-8690"
          - remote: "mswebench/cgal_m_cgal:pr-8688"
          - remote: "mswebench/cgal_m_cgal:pr-8631"
          - remote: "mswebench/cgal_m_cgal:pr-8539"
          - remote: "mswebench/cgal_m_cgal:pr-8518"
          - remote: "mswebench/cgal_m_cgal:pr-8349"
          - remote: "mswebench/cgal_m_cgal:pr-8201"
          - remote: "mswebench/cgal_m_cgal:pr-7927"
          - remote: "mswebench/cgal_m_cgal:pr-7798"
          - remote: "mswebench/cgal_m_cgal:pr-7595"
          - remote: "mswebench/cgal_m_cgal:pr-7410"
          - remote: "mswebench/cgal_m_cgal:pr-7397"
          - remote: "mswebench/cgal_m_cgal:pr-7230"
          - remote: "mswebench/cgal_m_cgal:pr-7095"
          - remote: "mswebench/cgal_m_cgal:pr-7094"
          - remote: "mswebench/cgal_m_cgal:pr-6883"
          - remote: "mswebench/cgal_m_cgal:pr-6809"
          - remote: "mswebench/cgal_m_cgal:pr-6727"
          - remote: "mswebench/cgal_m_cgal:pr-6707"
          - remote: "mswebench/cgal_m_cgal:pr-6704"
          - remote: "mswebench/cgal_m_cgal:pr-6686"
          - remote: "mswebench/cgal_m_cgal:pr-6650"
          - remote: "mswebench/cgal_m_cgal:pr-6550"
          - remote: "mswebench/cgal_m_cgal:pr-6412"
          - remote: "mswebench/cgal_m_cgal:pr-6287"
          - remote: "mswebench/cgal_m_cgal:pr-6154"
          - remote: "mswebench/cgal_m_cgal:pr-6120"
          - remote: "mswebench/cgal_m_cgal:pr-6084"
          - remote: "mswebench/cgal_m_cgal:pr-6020"
          - remote: "mswebench/cgal_m_cgal:pr-6012"
          - remote: "mswebench/cgal_m_cgal:pr-5937"
          - remote: "mswebench/cgal_m_cgal:pr-5884"
          - remote: "mswebench/cgal_m_cgal:pr-5868"
          - remote: "mswebench/cgal_m_cgal:pr-5837"
          - remote: "mswebench/cgal_m_cgal:pr-5705"
          - remote: "mswebench/cgal_m_cgal:pr-5689"
          - remote: "mswebench/cgal_m_cgal:pr-5510"
          - remote: "mswebench/cgal_m_cgal:pr-5435"
          - remote: "mswebench/cgal_m_cgal:pr-5409"
          - remote: "mswebench/cgal_m_cgal:pr-5407"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-31844"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-31590"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-31556"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-31384"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-31223"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-31156"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-31112"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-31096"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-30866"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-30697"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-30515"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-30275"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-29904"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-29899"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-29888"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-29656"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-29623"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-29612"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-29112"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-29022"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-29003"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-28998"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-28913"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-28872"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-28754"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-28685"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-28652"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-28587"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-28542"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-28539"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-28505"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-27969"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-27920"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-27622"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-27236"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-27165"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-27114"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-27113"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-27068"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-26909"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-26675"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-26514"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-26499"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-26410"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-26347"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-26203"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-26152"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-26094"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-26021"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-25943"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-25880"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-25812"
          - remote: "mswebench/bitcoin_m_bitcoin:pr-25729"


    steps:
      - name: Check Secrets
        run: |
          if [ -n "${{ secrets.ALIRUN_USER }}" ]; then echo "User is set"; else echo "User is EMPTY"; fi
          if [ -n "${{ secrets.ALIRUN_PWD }}" ]; then echo "Password is set"; else echo "Password is EMPTY"; fi
          
      - name: Login to Aliyun
        uses: docker/login-action@v2
        with:
          registry: crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIRUN_USER }}
          password: ${{ secrets.ALIRUN_PWD }}

      # - name: Pull, Tag and Push
      #   run: |
      #     # 强制指定架构并拉取
      #     docker pull --platform linux/amd64 ${{ matrix.remote }}
          
      #     # 打标签并推送到阿里云 (替换为你自己的命名空间)
      #     docker tag ${{ matrix.remote }} crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com/${{ matrix.remote }}
      #     docker push crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com/${{ matrix.remote }}
      
      - name: Sync Image with Skopeo
        run: |
          skopeo copy --all --src-tls-verify=false \
          --src-creds "${{ secrets.DOCKERHUB_USER }}:${{ secrets.DOCKERHUB_TOKEN }}" \
          --dest-creds "${{ secrets.ALIRUN_USER }}:${{ secrets.ALIRUN_PWD }}" \
          docker://docker.io/${{ matrix.remote }} \
          docker://crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com/${{ matrix.remote }}
