name: Docker Image Sync

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ================= 安全清理（只删没用的，绝不碰Docker）=================
      - name: 释放磁盘空间（安全版）
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/powershell
          sudo apt clean
          df -h  # 查看空间
          pwd

      # # ================= 安装工具 =================
      # - name: 安装 mc (MinIO Client)
      #   run: |
      #     wget -O /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc
      #     chmod +x /usr/local/bin/mc
      #     mc --version
          
      # - name: 配置移动云
      #   run: |
      #     mc alias set yidongyun https://eos-huhehaote-1.cmecloud.cn MKGF0ECFDCVJKGB33XPF MQbC0ZWz8bwVnN2c18UbxlMUWBzo5bnzyxPQtyJl

      # ================= 拉取镜像 =================
      - name: 拉取 Docker 镜像
        run: |
          docker pull --platform linux/amd64 lmsysorg/sglang:deepseek-v4-hopper

      # ================= 打包 =================
      - name: 保存为 tar 包
        run: |
          docker save -o deepseek-v4-hopper.tar lmsysorg/sglang:deepseek-v4-hopper

      # ================= 上传 =================
      - name: 上传到 GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deepseek-v4-hopper
          path: deepseek-v4-hopper.tar

      # 想直接传到移动云就打开下面这段（更快）
      # - name: 上传到移动云对象存储
      #   run: |
      #     mc cp deepseek-v4-hopper.tar yidongyun/cmjt-code/
