name: Bulk Docker Image Sync

on:
  workflow_dispatch: # 手动触发

jobs:
  sync-images:
    runs-on: ubuntu-latest
    strategy:
      # 矩阵配置：在这里列出所有你想要拉取的镜像
      matrix:
        include:
          - remote: "mswebench/fluent_m_fluent-bit:pr-8279"
          - remote: "mswebench/fluent_m_fluent-bit:pr-8062"
          - remote: "mswebench/fluent_m_fluent-bit:pr-4375"
          - remote: "mswebench/fluent_m_fluent-bit:pr-3487"
          - remote: "mswebench/fluent_m_fluent-bit:pr-2043"
          - remote: "mswebench/jqlang_m_jq:pr-2964"
          - remote: "mswebench/jqlang_m_jq:pr-2945"
          - remote: "mswebench/jqlang_m_jq:pr-2712"
          - remote: "mswebench/jqlang_m_jq:pr-2254"
          - remote: "mswebench/libgit2_m_libgit2:pr-6944"
          - remote: "mswebench/libgit2_m_libgit2:pr-6788"
          - remote: "mswebench/libgit2_m_libgit2:pr-6742"
          - remote: "mswebench/libgit2_m_libgit2:pr-6625"
          - remote: "mswebench/libgit2_m_libgit2:pr-6614"
          - remote: "mswebench/libgit2_m_libgit2:pr-6521"
          - remote: "mswebench/libgit2_m_libgit2:pr-6455"
          - remote: "mswebench/libgit2_m_libgit2:pr-6346"
          - remote: "mswebench/libgit2_m_libgit2:pr-6345"
          - remote: "mswebench/libgit2_m_libgit2:pr-6341"
          - remote: "mswebench/libgit2_m_libgit2:pr-6326"
          - remote: "mswebench/libgit2_m_libgit2:pr-6251"
          - remote: "mswebench/libgit2_m_libgit2:pr-6167"
          - remote: "mswebench/libgit2_m_libgit2:pr-6026"
          - remote: "mswebench/libgit2_m_libgit2:pr-5760"
          - remote: "mswebench/libgit2_m_libgit2:pr-5759"
          - remote: "mswebench/libgit2_m_libgit2:pr-5387"
          - remote: "mswebench/libgit2_m_libgit2:pr-5373"
          - remote: "mswebench/libgit2_m_libgit2:pr-5355"
          - remote: "mswebench/libgit2_m_libgit2:pr-5151"
          - remote: "mswebench/libgit2_m_libgit2:pr-5131"
          - remote: "mswebench/libgit2_m_libgit2:pr-4982"
          - remote: "mswebench/libgit2_m_libgit2:pr-4332"
          - remote: "mswebench/libgit2_m_libgit2:pr-3564"
          - remote: "mswebench/libgit2_m_libgit2:pr-663"
          - remote: "mswebench/libgit2_m_libgit2:pr-348"
          - remote: "mswebench/libsdlorg_m_sdl:pr-11946"
          - remote: "mswebench/libsdlorg_m_sdl:pr-11871"
          - remote: "mswebench/libsdlorg_m_sdl:pr-11546"
          - remote: "mswebench/libsdlorg_m_sdl:pr-11518"
          - remote: "mswebench/libsdlorg_m_sdl:pr-11203"
          - remote: "mswebench/libsdlorg_m_sdl:pr-11021"
          - remote: "mswebench/libsdlorg_m_sdl:pr-11003"
          - remote: "mswebench/libsdlorg_m_sdl:pr-11000"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10976"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10958"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10867"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10819"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10618"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10605"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10459"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10231"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10158"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10030"
          - remote: "mswebench/libsdlorg_m_sdl:pr-10010"
          - remote: "mswebench/libsdlorg_m_sdl:pr-9914"
          - remote: "mswebench/libsdlorg_m_sdl:pr-9889"
          - remote: "mswebench/libsdlorg_m_sdl:pr-9886"
          - remote: "mswebench/libsdlorg_m_sdl:pr-9856"
          - remote: "mswebench/libsdlorg_m_sdl:pr-9655"
          - remote: "mswebench/libsdlorg_m_sdl:pr-9297"
          - remote: "mswebench/libsdlorg_m_sdl:pr-9257"

    steps:
      - name: Check Secrets
        run: |
          if [ -n "${{ secrets.ALIRUN_USER }}" ]; then echo "User is set"; else echo "User is EMPTY"; fi
          if [ -n "${{ secrets.ALIRUN_PWD }}" ]; then echo "Password is set"; else echo "Password is EMPTY"; fi
          
      - name: Login to Aliyun
        uses: docker/login-action@v2
        with:
          registry: crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIRUN_USER }}
          password: ${{ secrets.ALIRUN_PWD }}

      # - name: Pull, Tag and Push
      #   run: |
      #     # 强制指定架构并拉取
      #     docker pull --platform linux/amd64 ${{ matrix.remote }}
          
      #     # 打标签并推送到阿里云 (替换为你自己的命名空间)
      #     docker tag ${{ matrix.remote }} crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com/${{ matrix.remote }}
      #     docker push crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com/${{ matrix.remote }}
      
      - name: Sync Image with Skopeo
        run: |
          skopeo copy --all --src-tls-verify=false \
          --src-creds "${{ secrets.DOCKERHUB_USER }}:${{ secrets.DOCKERHUB_TOKEN }}" \
          --dest-creds "${{ secrets.ALIRUN_USER }}:${{ secrets.ALIRUN_PWD }}" \
          docker://docker.io/${{ matrix.remote }} \
          docker://crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com/${{ matrix.remote }}
