name: Bulk Docker Image Sync

on:
  workflow_dispatch: # 手动触发

jobs:
  sync-images:
    runs-on: ubuntu-latest
    strategy:
      # 矩阵配置：在这里列出所有你想要拉取的镜像
      matrix:
        include:
          - remote: "mswebench/libsdl-org_m_sdl:pr-9170"
          - remote: "mswebench/libsdl-org_m_sdl:pr-8385"
          - remote: "mswebench/libsdl-org_m_sdl:pr-8247"
          - remote: "mswebench/libsdl-org_m_sdl:pr-8213"
          - remote: "mswebench/libsdl-org_m_sdl:pr-7923"
          - remote: "mswebench/libsdl-org_m_sdl:pr-7770"
          - remote: "mswebench/libsdl-org_m_sdl:pr-7671"
          - remote: "mswebench/libsdl-org_m_sdl:pr-7571"
          - remote: "mswebench/libsdl-org_m_sdl:pr-7395"
          - remote: "mswebench/libsdl-org_m_sdl:pr-5813"
          - remote: "mswebench/libsdl-org_m_sdl:pr-5727"
          - remote: "mswebench/mruby_m_mruby:pr-6442"
          - remote: "mswebench/mruby_m_mruby:pr-6440"
          - remote: "mswebench/mruby_m_mruby:pr-6412"
          - remote: "mswebench/mruby_m_mruby:pr-6391"
          - remote: "mswebench/mruby_m_mruby:pr-6305"
          - remote: "mswebench/mruby_m_mruby:pr-6091"
          - remote: "mswebench/mruby_m_mruby:pr-5084"
          - remote: "mswebench/mruby_m_mruby:pr-5038"
          - remote: "mswebench/mruby_m_mruby:pr-3649"
          - remote: "mswebench/mruby_m_mruby:pr-3594"
          - remote: "mswebench/mruby_m_mruby:pr-3571"
          - remote: "mswebench/mruby_m_mruby:pr-3570"
          - remote: "mswebench/mruby_m_mruby:pr-3365"
          - remote: "mswebench/mruby_m_mruby:pr-3174"
          - remote: "mswebench/mruby_m_mruby:pr-3080"
          - remote: "mswebench/mruby_m_mruby:pr-3065"
          - remote: "mswebench/mruby_m_mruby:pr-2885"
          - remote: "mswebench/mruby_m_mruby:pr-2828"
          - remote: "mswebench/mruby_m_mruby:pr-2784"
          - remote: "mswebench/mruby_m_mruby:pr-2521"
          - remote: "mswebench/mruby_m_mruby:pr-2370"
          - remote: "mswebench/mruby_m_mruby:pr-2261"
          - remote: "mswebench/mruby_m_mruby:pr-1985"
          - remote: "mswebench/mruby_m_mruby:pr-1832"
          - remote: "mswebench/mruby_m_mruby:pr-1545"
          - remote: "mswebench/mruby_m_mruby:pr-1505"
          - remote: "mswebench/php_m_php-src:pr-17835"
          - remote: "mswebench/php_m_php-src:pr-17405"
          - remote: "mswebench/php_m_php-src:pr-16158"
          - remote: "mswebench/php_m_php-src:pr-16129"
          - remote: "mswebench/php_m_php-src:pr-16025"
          - remote: "mswebench/php_m_php-src:pr-16006"
          - remote: "mswebench/php_m_php-src:pr-16001"
          - remote: "mswebench/php_m_php-src:pr-15825"
          - remote: "mswebench/php_m_php-src:pr-15733"
          - remote: "mswebench/php_m_php-src:pr-15717"
          - remote: "mswebench/php_m_php-src:pr-15676"
          - remote: "mswebench/php_m_php-src:pr-15494"

    steps:
      - name: Check Secrets
        run: |
          if [ -n "${{ secrets.ALIRUN_USER }}" ]; then echo "User is set"; else echo "User is EMPTY"; fi
          if [ -n "${{ secrets.ALIRUN_PWD }}" ]; then echo "Password is set"; else echo "Password is EMPTY"; fi
          
      - name: Login to Aliyun
        uses: docker/login-action@v2
        with:
          registry: crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIRUN_USER }}
          password: ${{ secrets.ALIRUN_PWD }}

      # - name: Pull, Tag and Push
      #   run: |
      #     # 强制指定架构并拉取
      #     docker pull --platform linux/amd64 ${{ matrix.remote }}
          
      #     # 打标签并推送到阿里云 (替换为你自己的命名空间)
      #     docker tag ${{ matrix.remote }} crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com/${{ matrix.remote }}
      #     docker push crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com/${{ matrix.remote }}
      
      - name: Sync Image with Skopeo
        run: |
          skopeo copy --all --src-tls-verify=false \
          --src-creds "${{ secrets.DOCKERHUB_USER }}:${{ secrets.DOCKERHUB_TOKEN }}" \
          --dest-creds "${{ secrets.ALIRUN_USER }}:${{ secrets.ALIRUN_PWD }}" \
          docker://docker.io/${{ matrix.remote }} \
          docker://crpi-xgbpniicu7dny74q.cn-hangzhou.personal.cr.aliyuncs.com/${{ matrix.remote }}
